### ISSUE TITLE
Use Alt Tags and Image Dimensions

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#100]
from #6: The JCE editor allows you add the Alternate Text to describe your image as well as add the dimensions right within the image upload tool.
Adding image dimensions to your images allows the "space" to load before the actual image does. This should help improve your load times a bit.
TinMCE the current default editor also supports alt image editing btw. 

Please go through all the content to verify that appropriate alt tags are in place.

**Comment by laisee** [comment]
move to prod(127) when its ready. no need to review unless there is some tool to check the code automatically
