### ISSUE TITLE
Ensure Consistent When Linking Internally

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#101]
Check all current published content to see if there are any direct references or links referrring to www.e-sports.cool .

We will standardize on http://e-sports.cool as the default reference and need the ensure consistency, please refer to #9:
https://moz.com/blog/seo-your-joomla-website-in-11-super-easy-steps
.

**Comment by laisee** [comment]
if this is ready, please apply any changes to prod(127)
