### ISSUE TITLE
Add top twitch steams per game landing page

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#105]
Insert a module showing top twitch channels for each game landing page

**Comment by jasonGonzales33** [comment]
http://45.58.40.76/jason/index.php/games/heroesofthestorm

Please review the link above. If the module is approved: i will apply to all game pages. Otherwise, please state what i should revise/add to the module

**Comment by laisee** [comment]
looks good, pls go ahead
