### ISSUE TITLE
popup - enhance look&feel. remove browser bug

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#106]
provide a better looking popup than what we have for sending cool, possibly JS, with field validation.

**Comment by laisee** [comment]
ensure the popup checks users balance (1st wallet address in user profile) and stops them sending any COOL if the NEM or COOL balance is too low. REST call to "http://esports-tx.herokuapp.com/wallet/<address-in-user-profile>" e.g. "http://esports-tx.herokuapp.com/wallet/NAVMJB-F32F7M-56MVBX-FNXSUM-3JDPIZ-RZ3RVZ-GR2Z"

**Comment by ppantilla** [comment]
for the "better looking part"  please take a look at these options, and prototype.  ill help you out with the wallet balance check part.  you can also look in the modules with the search term "cool" for all the custom implementation modules we have, on 76

**Comment by ppantilla** [comment]
https://www.sitepoint.com/14-jquery-modal-dialog-boxes/

**Comment by ppantilla** [comment]
please provide updates for this

**Comment by jasonGonzales33** [comment]
http://45.58.40.76/jason/index.php/games/rocketleague#

**Comment by jasonGonzales33** [comment]
link is the "new modal look", if look is ok.. I need assistance in finding where to place this modal (the send cool function location)

**Comment by ppantilla** [comment]
ill need to build it into my code so just sending me a copy will do, but before that, um, perhaps we can make it a bit subdued?  our  users will appreciate a more subtle but well designed modal.  gold coins are a bit too garish.  actually theres an unwritten rule on that in design for financial interfaces; cant have explicit depictions of money in financial apps.  Something about the psychology of depiction indicating your motives vs the trust you wish to build with clients etc.

**Comment by ppantilla** [comment]
if we can have a rounded edge modal with a shadow and a nice dark background that complements our current colors that would be good.  having a background image is ok but it shouldnt jump out at you.

**Comment by ppantilla** [comment]
subdued and complementary are key

**Comment by ppantilla** [comment]
also if you could make it smaller and use the fonts we use that would be great

**Comment by ppantilla** [comment]
background images should be fine but they should remain neutral, just like desktop wallpapers

**Comment by laisee** [comment]
I don't see this deployed at e-sports.cool site, please check if the code has been uploaded.

**Comment by jasonGonzales33** [comment]
ah, yes, i thought it was. I gave the code to peter he will integrate it with his code and migrate to 76 and prod. will close once this is done

**Comment by laisee** [comment]
Please close tickets when features are completed in prod(e-sports.cool)
only. Makes it easier to know whats 100% done. thanks.

**Comment by ppantilla** [comment]
i've tried to integrate this but there's something that isn't quite working.  I've put all the code into the module Send COOL Form v2 on 76.  If you'll notice there are tags for css <style> , and JS <script> along with the code, which is a facility afforded by Sourcerer, a 3rd party system plugin that is not intrinsic to Joomla, that allows you to declare css and JS within a single module.  

This has been very useful for us thus far, but when I put all the code it doesn't seem to get called.  Please work through and correct.  Use Send COOL Form v1 module as a reference on how it currently works, and do not edit it, as it also serves as a backup copy.

Reassigning back to you for remediation.

**Comment by jasonGonzales33** [comment]
got the modal to work on 76

**Comment by jasonGonzales33** [comment]
but it showing this error upon form action (note that it also shows this error with the original code)

Oct 24 16:00:41 esports.web /var/www/html/components/com_sendcool.php: COOL Tokens sent to NAVG3S3AXTMVAZDTT2HBGCEV53VM2JHKH65DWBKP - Error: Unknown address "NDRPEKJIHDK4E2YGCTH6NJT24IALWYK2HIV4IQI4" used in Transaction/new method

**Comment by ppantilla** [comment]
its in the send cool button module pala.  yeah lets take a look first thing tom

**Comment by laisee** [comment]
fix the last issue on clicking browser back button, then this can be closed.

Note that style of the popup is bit different to the general site && easy social. Can sync all three styles in next design review
