### ISSUE TITLE
send cool returning insufficient balance error

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#108]
Oct 13 17:16:19 esports.web /var/www/html/components/com_sendcool.php:  COOL Tokens sent to NDNFQVT4ALPPDL5QAZ4EEFZHG2GIFJ4ZXNAPBTLO - {"innerTransactionHash":{},"code":5,"type":1,"message":"FAILURE_INSUFFICIENT_BALANCE","transactionHash":{"data":"dcd19ae7a37bdc01213a09b1673f8e875e304843e022460c34eedec868f5cb08"}}
Oct 13 18:57:39 esports.web /var/www/html/components/com_sendcool.php:  COOL Tokens sent to NDNFQVT4ALPPDL5QAZ4EEFZHG2GIFJ4ZXNAPBTLO - {"innerTransactionHash":{},"code":5,"type":1,"message":"FAILURE_INSUFFICIENT_BALANCE","transactionHash":{"data":"26450142b525796d9e2f704fbb30978cafac7600630e1dd66be49fe77e36f7e5"}}
Oct 13 20:04:49 esports.web /var/www/html/components/com_sendcool.php:  COOL Tokens sent to NDNFQVT4ALPPDL5QAZ4EEFZHG2GIFJ4ZXNAPBTLO - {"innerTransactionHash":{},"code":5,"type":1,"message":"FAILURE_INSUFFICIENT_BALANCE","transactionHash":{"data":"385fcec2117f8ce0b80078c1c7d73c25c7855e899666edacdb529fc3ec527c85"}}

**Comment by laisee** [comment]
taking a look at this now. possibly the private keys are not correctly associated with wallet addresses in the wallet svc.

**Comment by laisee** [comment]
caused by mismatch of keys vs wallet address
