### ISSUE TITLE
Construct Tournament Rules (for first tournament)

### ISSUE THREAD

**Issue by jasonGonzales33** [e-sportsdotcool/esports.web#114]

**Comment by jasonGonzales33** [comment]
this is what I came up with so far
https://anotepad.com/notes/qjr7q2

**Comment by ppantilla** [comment]
lets touch on scoring, describing  how the knockout system works, etc

**Comment by ppantilla** [comment]
maybe refer to the guidelines we went over together

**Comment by jasonGonzales33** [comment]
this is the guidelines we went over
http://archive.gathering.org/tg13/files/content/game/DOTA2%20-%20Rules-%20EN.pdf

**Comment by jasonGonzales33** [comment]
for the individual player scoring: i'll show you guys a dota 2 replay tomorrow, the game already has rubrics for that.

 for the Single Knockout system: if a team loses, the team can no longer compete. The winner will advance in the bracket. Theoretically, the champion has 0 loses.

**Comment by jasonGonzales33** [comment]
updated the draft
https://anotepad.com/notes/qjr7q2
