### ISSUE TITLE
Blend the blue/dark grey backgrounds

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#115]
Home page has two background colors - blue and dark grey because the styles of the site and easy social are not synchronized. 

Update the CSS so that consistent styling used across the page, same for any other pages affected.

**Comment by ppantilla** [comment]
blended es / main content area into a single grey

**Comment by laisee** [comment]
Looking at prod, now we have blue background in header/footer and grey in the middle. Can we change easy social to use the blue background instead of grey? It will look much better with one color scheme from top to bottom

**Comment by ppantilla** [comment]
will see, initially we did this bec the css was all over the place, but its worth a look now in this version

**Comment by ppantilla** [comment]
let me know if this looks like something you can work on.

**Comment by ppantilla** [comment]
stiill working on the menu top border  but otherwise done.
