### ISSUE TITLE
Error in home page on 76 instance

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#117]
see attached.

**Comment by laisee** [comment]
![Screen Shot 2017-10-21 at 9.48.21 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236456f26b7191a371f116234f5d5e5edd3c4a4356bcbbd671f3e57862804e0ee4d66f0b74c36914ffe9844de901ba27de1980e3bdd81dd2f42f67b6d5db1063474f4dcbed5727a19e41c95df643e44855a3103363ef752431.png)

**Comment by ppantilla** [comment]
putting this back to error reporting 0 and keeping in ready, as the cool total code also needs a proper rewrite for error handling.

**Comment by laisee** [comment]
Pls update the code to log errors to papertrail. I thought we had added some code already to handle any error on checking each balance per address?

**Comment by ppantilla** [comment]
we left notices and warnings out to lessen the log volume.  i've adjusted the error reporting levels at code level so this shouldn't bother us for the cool total and widget modules.
