### ISSUE TITLE
Change Joomsport Modules Style and Implement Joomsport Menu Items

### ISSUE THREAD

**Issue by jasonGonzales33** [e-sportsdotcool/esports.web#118]
change css to adjust to e-sports theme

**Comment by jasonGonzales33** [comment]
will also implement a menu item, 'Tournament' with submenus: 'Tournament List' and 'Player Registration'

**Comment by jasonGonzales33** [comment]
moved "Tournaments" as submenu to Home as the menu is crowded

**Comment by jasonGonzales33** [comment]
please review the newly styled joomsport pages. will migrate to prod once approved.
you can access it through submenu Tournaments

**Comment by laisee** [comment]
Pages look ok, with caveat that included content (i.e. all of easysocial, joomsports) sits on different background color than the site hosting it. I have raised a ticket for sync'ing the web site style in future.

**Comment by jasonGonzales33** [comment]
moved to prod, and tested. closing this ticket now

**Comment by jasonGonzales33** [comment]
got rid of the test data, however, since the data was not legitimate
