### ISSUE TITLE
Tournament signup 

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#120]
Need the signup form tested and working on Prod today.   Current form in staging has no title and dark letters and is hard to read, so some css needs to be fixed for that to be user friendly.

Form needs to be inviting to use.

Also, we'll need a team signup.  I think the easiest way to do this is to create an easysocial event and provide mechanics there.   I suggest having the teams setup their own team page on e-sports.cool ( refrain from saying Easysocial as thats propreitary to us) where they can organize themselves online.

**Comment by jasonGonzales33** [comment]
check registration mechanics on the event description

**Comment by jasonGonzales33** [comment]
We decided to drop the player registration joomsport page as it is pretty useless. Instead posted mechanics on how to register on the event page. Closing this now
