### ISSUE TITLE
Promote Killing Spree online

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#124]
Do the actual social media engagements.  share, promote and answer questions on the FB page

**Comment by laisee** [comment]
Send me links to copy out on twitter, Instagram etc. Also nice if we show
tambayan so Hoffman sees some marketing benefit for his involvement

**Comment by laisee** [comment]
didnt receive any items to promote, but send anything available now so I can mention the event as completed & successful
