### ISSUE TITLE
Killing Spree Tournament: Post tournament organization

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#130]
Ensure that the winners receive their prizes, that participants receive their t-shirt after they achieve 5 signups on the site.  

Join all created team groups and other interest groups created by the new signups (if any) to actively promote and share news and updates.

**Comment by laisee** [comment]
also perhaps a thank you to hoffman plus t-shirt? And, ofc, we need to see what worked, what can be improved and if Hoffman will allow another tournament in future.

**Comment by laisee** [comment]
all prizes handed out.
