### ISSUE TITLE
Show user balance on Send COOL popup

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#135]
Show balance + any transactions in progress so user knows what they can send.

Peter: spec this one out and show Jason where he can get the balance info (leave the task of finding in-progress transactions)

**Comment by jasonGonzales33** [comment]
added balance on the popup & back button no longer triggers the popup. please review

**Comment by laisee** [comment]
Looks good and works much better now.

**Comment by ppantilla** [comment]
Perf enhancement code, alternative to  getDbo () and getrow, getrows etc

$user = ES::user($userId);

// if you are running EasySocial version prior to 2.x
$user = FD::user($userId);

$username = $user->getUserName();

* $user->getFieldValue("CUSTOM_FIELD_KEY";); - This is the pre-formatted value 
* $user->getFieldData("CUSTOM_FIELD_KEY";); - This is the raw data from the database
