### ISSUE TITLE
Killing Spree Tournament: Video Management

### ISSUE THREAD

**Issue by jasonGonzales33** [e-sportsdotcool/esports.web#137]
-Download replays
-Use OBS/Fraps to record (into video) the code-level replay
-Upload matches to Twitch
-Create Youtube for e-sports.cool
-Upload matches to Youtube
-Advertise the channels

**Comment by jasonGonzales33** [comment]
https://www.twitch.tv/videos/188543310
The first match in COOL Games: Killing Spree

**Comment by jasonGonzales33** [comment]
having trouble with making video size smaller. will upload all of the videos as soon as this is resolved

**Comment by ppantilla** [comment]
just a note , was looking at one of the uploaded vids, couldnt see the scores too well

**Comment by jasonGonzales33** [comment]
this is the best possible quality my pc can record, unfortunately
