### ISSUE TITLE
Notify user that they have received COOL.

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#139]
Send a message to a user when another user has successfully sent COOL to them.

recommended code + notes from Easysocial:

<?php
require_once(JPATH_ROOT . '/administrator/components/com_easysocial/includes/easysocial.php');

$conversation = ES::conversation();
$data = array(
    'message' => 'hello world',
    'uid' => $targetUserId
);

$conversation->bind($data);
$conversation->save();

Support msg: 
You can look at the bind method in /administrator/components/com_easysocial/includes/conversation/conversation.php if you want something fancy

Although the snippet most likely will be able to address our needs.  Will probably go into a new function in /components/com_sendcool

**Comment by jasonGonzales33** [comment]
made simple changes to the code at /administrator/components/com_easysocial/includes/conversation/conversation.php

**Comment by jasonGonzales33** [comment]
had to comment out line 367 because message input did not come from user but from hard code. in any case, code is tested and ready to be deployed to 76 and prod

**Comment by jasonGonzales33** [comment]
for future reference: this is the code commented out //return false;

**Comment by jasonGonzales33** [comment]
code deployed at prod. closing
