### ISSUE TITLE
Display send COOL notices in user activity stream

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#140]
Notices i.e. "You send __ COOL to ___" or  " _____ sent you __ COOL " should show up in your activity feed

**Comment by jasonGonzales33** [comment]
deployed at prod. 76 is acting funny though. could be redis function issue? some variables are returning users from prod, not 76. prod is 100% though. closing this

**Comment by jasonGonzales33** [comment]
you can check via activity log or profile feed upon cool transfer success

**Comment by jasonGonzales33** [comment]
nevermind - 76 works perfect as well. forgot that we had fix code for 76
