### ISSUE TITLE
Create timeline entries for COOL received / sent events

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#143]
COOL sending and receiving must be reflected in timeline.

**Comment by ppantilla** [comment]
asked for implementation recommendations from ES, will implement along with the message notification code.

**Comment by laisee** [comment]
This is working now? Or we want to implement again using different approach.

**Comment by ppantilla** [comment]
@jasonGonzales33  i am receiving timeline entries but I'd like to check the implementation.  Could you point out where your code is for this?

**Comment by jasonGonzales33** [comment]
It is at /components/com_sendcool/controller.php

**Comment by jasonGonzales33** [comment]
At the bottom you will see the code for easy social streams

**Comment by jasonGonzales33** [comment]
Conversation notification code is also there

**Comment by ppantilla** [comment]
Reviewed.  looks good.  Did you test whether the timeline entries get created for different scenarios?

**Comment by jasonGonzales33** [comment]
yes it has handling . it only gets created upon success
