### ISSUE TITLE
COOL Balance not very distinct in UI

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#146]
The Cool balance does not show up against the background very well now. Should use different fonts, styles or colors to make it easy to view.

**Comment by laisee** [comment]
![Screen Shot 2017-11-09 at 4.21.17 PM.png](https://waffleio-direct-uploads-

production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226454fa6b7191a37cf1102a4f5e585ecc3c4a4356bcbbd671f3e57862804e0ee4d66f0b74c36914ffe9844de901ba27de1980e3bdd81dd2f42f67b6d5db1063474f4dcbed5727a19e41c95df74be34c50ac133363e57f2431.png)

**Comment by ppantilla** [comment]
will take this one
