### ISSUE TITLE
Disable Send COOL Button if viewing own profile

### ISSUE THREAD

**Issue by jasonGonzales33** [e-sportsdotcool/esports.web#149]
Transition to Gantry 5 seems to have disabled the  PHP code for disabling the button

**Comment by laisee** [comment]
Guess we have to re-enable ... ;-)

Peter, can you check on this one?

**Comment by ppantilla** [comment]
alright

**Comment by ppantilla** [comment]
@jasonGonzales33 the code for that is normally in the module.  took a look at the old code but cant find where that was implemented.    Do you recall where that was?

**Comment by ppantilla** [comment]
done, deployed to prod. and validated.  Closing.
