### ISSUE TITLE
Enable users to add Steam profile link

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#150]
Add a field to users e-sports profile so that the steam user URL can be added, 

Examples from Killing Spree winners are:
http://steamcommunity.com/id/SapporoDotes
http://steamcommunity.com/profiles/76561198159015206
http://steamcommunity.com/id/charlespogi

The url can help us to ,link to their steam account and display details on e-sports.cool like handle, assets, rating, etc

**Comment by ppantilla** [comment]
@laisee  will need your  help to get developer key: 
To start using the api, you need to get a developer key. You can get it by this link: get-steam-div-key.http://steamcommunity.com/dev/apikey

**Comment by ppantilla** [comment]
done.
