### ISSUE TITLE
Implement Steam API

### ISSUE THREAD

**Issue by jasonGonzales33** [e-sportsdotcool/esports.web#153]
1. verify whether steam web api can be used without a login
2. verify what services are available using our API key, with this as reference:
All interfaces and method are self-documented through the ISteamWebAPIUtil/GetSupportedAPIList call. This can be found at the URLs below.
When passed a key=<your API key> parameter, GetSupportedAPIList will show all APIs that your key can access. Without it (as above), it only displays APIs that do not require an API key.

more detailed references for the API at: https://partner.steamgames.com/doc/webapi_overview

https://partner.steamgames.com/doc/webapi

**Comment by jasonGonzales33** [comment]
Just an update: having trouble atm when user logs on steam via the site. This is the error - http://docs.gantry.org/gantry5/troubleshooting/max-nesting-level
not sure what is going on since i did not recall installing xdebug before. Will continue digging

**Comment by ppantilla** [comment]
im not seeing this please replicate on another test userid.

**Comment by jasonGonzales33** [comment]
it is at 76 now when you view your profile

**Comment by jasonGonzales33** [comment]
click on the steam button and it will take you to the login page. kindly log in and you will see the error. based on the message it occurs on the gantry code (loops more than 100 times on the function for some reason)

**Comment by jasonGonzales33** [comment]
click on the steam button and it will take you to the login page. kindly log in and you will see the error. based on the message it occurs on the gantry code (recursion trap - it calls itself more than 100 times). It has something to do with xdebug, according to my research, but i do not recall installing it

**Comment by jasonGonzales33** [comment]
i posted questions on:
Joomla - https://forum.joomla.org/viewtopic.php?f=706&t=957005&p=3503400#p3503400
stackoverflow - https://stackoverflow.com/questions/47426555/joomla-maximum-function-nesting-level-of-100-reached-aborting/47435375#47435375

**Comment by ppantilla** [comment]
Further relevant information from https://developer.valvesoftware.com/wiki/Steam_Web_API:

Calling Service interfaces

There is a new style of WebAPI which we refer to as "Services". They function in many ways like the WebAPIs you are used to, the main difference being that all service APIs will accept their arguments as a single JSON blob in addition to taking them as GET or POST parameters. To pass in data as JSON, invoke the webapi with a parameter set like:
?key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&format=json&input_json={"steamid":76561197972495328}
Note that the JSON will need to be URL-encoded. The "key" and "format" fields should still be passed as separate parameters, as before. POST requests are supported as well.
You can identify if a WebAPI is a "Service" by the name of the interface; if it ends in "Service" like "IPlayerService", then it supports this additional method of passing parameter data. Some Service methods have parameters that are more complex structures and require this different input format.

**Comment by ppantilla** [comment]
More leading information on the API :

Steam exposes an HTTP based Web API which can be used to access many Steamworks features. The API contains public methods that can be accessed from any application capable of making an HTTP request, such as game client or server. The API also contains protected methods that require authentication and are intended to be accessed from trusted back-end applications.

As an example, Web API methods are commonly used by a secure publisher server to:
Verify a Steam user's credentials with that server
Check if a user owns a particular application
Set or retrieve a user's stats, achievements or leaderboard scores
Execute an in-game purchase

**Comment by ppantilla** [comment]
ultimately cujstom CURL calls and parsing JSON would probably be enough.

**Comment by ppantilla** [comment]
and if we can make direct calls to the API using the browser with valid keys inserted into the call params that would confirm that we dont need to log into steam to get what we need.

**Comment by laisee** [comment]
Test each call using postman app. Steam requires oauth login AFAIK

**Comment by jasonGonzales33** [comment]
references:

test calls & documentation = https://lab.xpaw.me/steam_api_documentation.html
top csgo player for steam id test - https://www.steamidfinder.com/lookup/pashaBiceps

**Comment by laisee** [comment]
found this site for getting steam accounts using id32, id64, handle or profile URL: https://steamid.xyz/293548059

**Comment by ppantilla** [comment]
thanks we found some top player steam ids to browse as well off of the forums

**Comment by jasonGonzales33** [comment]
ISteamUser/ResolveVanityURL --> Method for Custom URL to Steam ID 64
e.g. tinwald will return 76561198253813787

**Comment by ppantilla** [comment]
is this a placeholder?
