### ISSUE TITLE
Add Steam badges/icons on user profile

### ISSUE THREAD

**Issue by jasonGonzales33** [e-sportsdotcool/esports.web#154]
Site participation such as but not limited to: posting events, posting comments, etc

**Comment by jasonGonzales33** [comment]
Update: I am now able to create new achievements/badges. Just need to design the image for the badges itself

**Comment by jasonGonzales33** [comment]
Ok. Ready to be deployed. I have covered posting events and comments. Please post here more suggestions on new achievents/badges i need to work on

**Comment by laisee** [comment]
Can I see how this looks on non-prod instance?

**Comment by jasonGonzales33** [comment]
It is at 76 instance now. You should get the badges now if you create an event or post a comment. It should notify you aswell and show the badge on your profile

**Comment by laisee** [comment]
Two issues

1. When I click on the steam login it gives an error
![Screen Shot 2017-11-25 at 10.32.30 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f66b7191a379ef0c2853415c4ebc21254d58eeb9cb74fce36f34985619e8d86a5d20c63845a9ebd319ed57ba208c1ad3b3e98b1e91fa2137a5dad11b61435c52dcbd4f3fb29842c259f34ae04b57a41b366ae373366e0a.png)

2. Adding an event doesn't add any badges to my profile
![Screen Shot 2017-11-25 at 10.39.08 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f66b7191a379ef0c2858415f46bc21254d58eeb9cb74fce36f34985619e8d86a5d20c63845a9ebd319ed57ba208c1ad3b3e98b1e91fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ae04b57a41b3064ee71316e0a.png)

**Comment by laisee** [comment]
Please prepare some test cases that I can follow through and try out, attaching screen shot with before/after views so I can review the changes tomorrow (Sunday). 

I don't have enough time right now to guess how the new features might work. Please be explicit in what the features do and how I will know if they are working.

**Comment by laisee** [comment]
update: can see "event creator" badge after refreshing the web page & cache. This is OK, but I'd rather be showing Steam badges and profile details.

**Comment by jasonGonzales33** [comment]
could not get the images of the steam badges as the json data returned did not contain the image url

found this useful link however: https://stackoverflow.com/questions/36328351/why-cant-i-use-php-curl-to-get-steam-user-profiles-and-how-to-get-steam-badge-i?noredirect=1&lq=1

will try  file_get_contents()  instead of the web api

**Comment by laisee** [comment]
Using a python lib (steamodd) and API key I was able to get the URL for the
badge files, so I guess the data is available somehow.

**Comment by jasonGonzales33** [comment]
![Selection_015.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cba5677fb6900011a39579/125516c66e82c728ace21e0d46db9196268197a080e78013f508b2d86b56357c2301a03f32dfa17de61529055f5a1aa912095916aaf9892cf3e039258b0e5affcd7f1d2598694ef1e1c84afd13b0328a468fb7b98b4dc7e03824ee8c8e4f3d0c48.png)

**Comment by jasonGonzales33** [comment]
deployed on 76, please check if there is any error

**Comment by jasonGonzales33** [comment]
i put my steam url as tinwald to test (because i do not have any badges)

**Comment by jasonGonzales33** [comment]
found error when easy social steam url field is empty. will implement handling for this

**Comment by jasonGonzales33** [comment]
handling implemented. please review if i need to change anything

**Comment by laisee** [comment]
tested using http://steamcommunity.com/id/tinwald. I can see the badges created by Easy Social ("event creator") but nothing from Steam. Is there any lookup on steam account info yet?

**Comment by jasonGonzales33** [comment]
tested and verified. this is on prod now. closing
