### ISSUE TITLE
UI Redesign: Create User Journey

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#159]
Target Review Date:  12/6
This is the design that defines what the user will see as they progress through the site.  This will be done using static HTML to be integrated as a Gantry 5 template.

**Comment by ppantilla** [comment]
outline is complete, will take this straight into the template for completion by Dec 14

**Comment by laisee** [comment]
I’d like to know what the end result will be in terms of features and UI changes. Can you list the changes to the site, so I can understand

 

gavin

**Comment by ppantilla** [comment]
Features:
1. Responsive design including wallet and transaction log.
2. Search for sale items, display search results with links to item detail page.  
3. Cron based import of items from steam, with user checkbox to designate whether item is set for sale in the market 
4. Search for 


UI Changes:
1. Design will

**Comment by laisee** [comment]
I am looking at the new display on staging. It doesn't look complete yet, please confirm if its the final look & feel for new design
Points:
- too much red color used to highlight links and sections
- multiple login links 
- Clicking on "Community", then "Steam Inventory" leads to the league/tournament management functions - is that right?
- "What is the NEM" should be "What is NEM"
- Remove mention of COOL for now, we may release a new token for trading digital content.
- click on Games leads to incomplete page e.g. http://45.58.40.76/index.php?option=com_content&view=article&id=29&Itemid=201
- remove "Savings Calculator"

Overall I am not convinced the new look is an improvement on  previous look. The current code on staging doesn't help me to imagine the new site as a consistent, workable UX.

**Comment by ppantilla** [comment]
outline / basic implem single template up on staging, currently working out login and display bugs
