### ISSUE TITLE
Create FAQ content

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#164]
need to prepare FAQ content based loosely on the lootmarket FAQs.

Lets keep them in one accordion type module.

https://www.lootmarket.com/faq

**Comment by jasonGonzales33** [comment]
[e-sports.cool FAQ Dec-5-2017.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cba5677fb6900011a39579/125516c66e82c728ace21e0d46edd989338d91bd9ca7bc4cab51b0b2087767572c07ee7e3dd7b379e80037431f1d11f6140b1b56f6eb8c22a1b468708f080ebe806b0d22c63d16f9ee874abe53eb32975dc7e7e2de139db17770a599855d3f190f198cfe5f31a79b49c85cf64ee15f18.txt)

these are the faq that apply to us..for now
please review

**Comment by ppantilla** [comment]
Thanks for this draft.  Will develop as the design progresses. Closing.
