### ISSUE TITLE
Customize Login/Register with New Styling

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#170]
Create a new login register dialog that redirects to a new dashboard that displays just selected ES functionality:  Activity Stream / Groups / Pages / Events / People / Wallet / Transaction Log

**Comment by ppantilla** [comment]
WIP on staging.  still with issues.

**Comment by ppantilla** [comment]
subticket for 159; will review and deploy as group this week

**Comment by ppantilla** [comment]
implemented in staging

**Comment by laisee** [comment]
Will take a look after lunch.

**Comment by ppantilla** [comment]
done and deployed to prod.  closing.

**Comment by laisee** [comment]
Thanks,  reviewing tomorrow am.
