### ISSUE TITLE
Create Search Skin Artists Dialog and Results Page

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#171]
Involves allowing users to identify as a skin artist and accept work as such.  Subtasks for this would be to implement a contracting function.

**Comment by ppantilla** [comment]
Search for artists by use of an internal field that serves as a flag
clicking on a search result will link to the user profile that also displays the current items for sale by that artist.

**Comment by laisee** [comment]
Can I see this on staging server?

**Comment by jasonGonzales33** [comment]
It's deployed at production. Check Workshop menu items

**Comment by ppantilla** [comment]
would be good to be able search for a name.  how do you designate yourself as an artist that wants to sell something i.e. basically set the flag for the field?
