### ISSUE TITLE
Display wallet totals & transactions on Wallet tab

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#174]
display wallet transactions in a bootstrap popover.

**Comment by jasonGonzales33** [comment]
decided to go with the modal.. which is a lot better in my opinion. code deployed to prod.. closing

**Comment by ppantilla** [comment]
some adjustments, can you adjust the styling so that its consistent with the new design?  background should be dark blue, set gridlines to be #ff0000 red, and font-family to Rubik.

**Comment by jasonGonzales33** [comment]
Done - also got rid of the background-image; please review

**Comment by laisee** [comment]
How can I test out the new function from end to end?

**Comment by jasonGonzales33** [comment]
![Untitled.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cba5677fb6900011a39579/125516c66e82c728ace21e0d46dd9a8e2a968fac8babf301b44fff9e2c4533317346f67227d7e778ea462e020e591cfa41585811aafcdc2af4e72e6c981e5ab38532022d8c6853beb2901eb70bbb258a4b8cb0b98d4cc9ed3b26f5c6.png)

**Comment by jasonGonzales33** [comment]
click the show cool accounts button (on production site)
working on different style though, as per peter's request

**Comment by jasonGonzales33** [comment]
also: after clicking on the button, click on the wallet that you want to review your transactions

**Comment by jasonGonzales33** [comment]
New style is done and is at production site.. will close once reviewed - if no changes to be done
