### ISSUE TITLE
Custom payment plugin for COOL

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#177]
create COOL Sellacious payment plugin.  This is basically a send of COOL from the wallet of the buyer to the wallet of the seller.

**Comment by ppantilla** [comment]
most likely this will be a hack of the existing e-wallet plugin

**Comment by jasonGonzales33** [comment]
Working COOL payment method in Custom Skin Purchase is fully functional and deployed to production site.

**Comment by laisee** [comment]
"COOL"

I will login and test after the conference today

Gavin
