### ISSUE TITLE
Can't login and can't request pwd reset

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#179]
Can't login and can't request pwd reset

**Comment by jasonGonzales33** [comment]
i can confirm password reset is not working, although i seem to be logging in just fine with correct credentials. i'll look into this

**Comment by laisee** [comment]
K, need the reset to be done by another admin.

**Comment by ppantilla** [comment]
sorry the domain isnrt resolving properly to the default home page menu link, still working this out.

**Comment by laisee** [comment]
It's ok, jason changed the password manually.

Gavin

**Comment by ppantilla** [comment]
the home page is http://e-sports.cool/index.php?option=com_content&view=article&id=67&Itemid=101 for now

**Comment by jasonGonzales33** [comment]
Works now; e-mail sent for password reset is stored in the Spam though (tested using Gmail)
