### ISSUE TITLE
Steam Inventory to contain all marketable items along with a trigger to set or disable sale

### ISSUE THREAD

**Issue by jasonGonzales33** [e-sportsdotcool/esports.web#186]
Currently the Steam Inventory contains all of the users' Steam items. Change this (if it is possible) to only display items that are marketable && marked for sale

**Comment by jasonGonzales33** [comment]
Description change: Inventory should contain all marketable items along with a trigger to set or disable sale

**Comment by jasonGonzales33** [comment]
this is done as well. deployed on staging

**Comment by laisee** [comment]
Will take a look this afternoon
