### ISSUE TITLE
Joomsport re-style of css files to match site theme

### ISSUE THREAD

**Issue by jasonGonzales33** [e-sportsdotcool/esports.web#187]
change css and js elements of all screens  to be cosnistent with the template.

**Comment by ppantilla** [comment]
http://45.58.40.76/tournaments/matches 
ERROR! SEASON ID not DEFINED

**Comment by jasonGonzales33** [comment]
this is done - please review

**Comment by jasonGonzales33** [comment]
updated

**Comment by jasonGonzales33** [comment]
assignment: need to change text from white to #ede8e8

**Comment by jasonGonzales33** [comment]
assignment: change clicks to players redirection (currently it is bugged). also team page text is set to dark - change to light

**Comment by jasonGonzales33** [comment]
resolved redirection bug. styling is done as well
