### ISSUE TITLE
restore transaction display

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#188]
investigate whether its a simple fix to switch the transacxtion display from the current version or whether we need to switch code back from a previous version

**Comment by jasonGonzales33** [comment]
plugged in the modal i worked on on staging. will this do?

**Comment by ppantilla** [comment]
this is good, just need to do a few adjustments:
1. i think that each row occupies too much vertical space.  couold we reduce the space between lines by about 5px?  I think that the fon't size is a bit bigger than in the community page, perhaps you could make it the same size.

**Comment by ppantilla** [comment]
2nd review: 

this is better just need to replace the red with the "show cool accounts" button blue
