### ISSUE TITLE
Gain knowledge, verify, and prototype how skins trading will work

### ISSUE THREAD

**Issue by jasonGonzales33** [e-sportsdotcool/esports.web#194]
This includes but is not limited to browsing and participating on sites that do skins trading,  extensive research on steam APIs (possibly market APIs - if there are), and 
prototyping.

**Comment by ppantilla** [comment]
please post this weeks developments for this here

**Comment by jasonGonzales33** [comment]
- login using steam. good PHP library --> (https://github.com/SmItH197/SteamAuthentication)
- user needs to set trade URL on the site. user can get this at (https://steamcommunity.com/profiles/<STEAM_ID>/tradeoffers/privacy#create_new_url_btn)
- user needs to set inventory settings to public via (https://steamcommunity.com/profiles/<STEAM_ID>/edit/settings)
- the way this works is the user sends us a trade offer ("us" meaning "our" steam account - meaning, we have to have steam accounts that will be used to operate trades)

im still doing research on how to handle trade offers though. Steam IEconService APIs arent helpful enough

**Comment by jasonGonzales33** [comment]
Update: I have code ready to be tested... Just need to wait for the pompokey steam account to be trade enabled (still restricted - 6 days remaining). Now I need to work on the Steam Guard Mobile Authenticator so that users will not get the 15-day trade hold (ticket 231).

**Comment by jasonGonzales33** [comment]
![15.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cba5677fb6900011a39579/125516c66e82c728ace21e0d46b9c1d86fc093bb80e3ba40b01faad67c1f70212d54f62f2586e27ebd442b51580a18a914590d15eee59b69f7e8682fd70541b8937f5566c7351badbd801cb708bc22824786b0b89801.png)

According to Steam, trading restrictions for 'pompokey' will end on Thursday at around 4 PM, GMT+8

**Comment by jasonGonzales33** [comment]
Brought a few things from the market (has 7-day trade hold though since it was purchased from Steam Market NOT a trade). Bot is functioning well and code is tested. Of course as expected: the message returns failed trade offers because of the trade hold.. Other methods return positive results though.

Spent Around 4 SGD ('pompokey' account).

Ready to deploy the real thing. I think it will work out well, just need to wait for the trade holds on the items i brought to test the real thing.. closing this  now (will post updates on ticket 213 once the whole market is functioning)

**Comment by laisee** [comment]
Please go ahead and deploy
