### ISSUE TITLE
Search for sale items

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#195]
clicking on the search for items in the menu should popup a search box modal that allows users to search for sale items.

These are items in the users sellacious items for sale that have been read in from steam.

**Comment by ppantilla** [comment]
this should work basically the same way as  here: http://demo.sellacious.com/squick/

**Comment by jasonGonzales33** [comment]
not sure what the issue is but i tried the latest versions 1.5.1 and 1.5.2 all search modules and menu items do not work

**Comment by jasonGonzales33** [comment]
I will go take a look at what Rafael was suggesting - Virtuemart. it seems Sellacious is still at its early stages and with only a small community (and my 2-month old forum question still has zero responses)

**Comment by ppantilla** [comment]
Alright.  Was going to suggest that.  Just as a last ditch, can you verify it on your /jason (doesn't matter if your version of the code there is super old) that sellacious search is still broken even if we use a stock template?  if it works, then it might just be a matter of css or styling?

**Comment by jasonGonzales33** [comment]
![sellacious support.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cba5677fb6900011a39579/125516c66e82c728ace21e0d46fb91962f8380a080fcac03b748e084265433316546b3397f8fe62bab0021435a5649ae15585a10f9aad82df4e03c708d095de8846c0d25d42103eee9dc4be05ce36ade0d97bcae8b45cae93824ee838f473e180d1a89ff4f78.PNG)

**Comment by jasonGonzales33** [comment]
since this is the issue, i am now currently coding my own search implementation

**Comment by ppantilla** [comment]
also part of this solution is deciding whether you would like to entertain using virtuemart or any other store component.

**Comment by jasonGonzales33** [comment]
Virtuemart is intended to be single vendor. (ive tried it, even looked at database) my findings are explained further on ticket 196. Sellacious is still at its early stages but i will be more comfortable working  with it (for now) and I have it planned out

**Comment by jasonGonzales33** [comment]
i have coded a functioning search module for the products in staging now, just needs css changes & to finalize the 'button to cart' functionality

**Comment by ppantilla** [comment]
great !

**Comment by ppantilla** [comment]
suggest that you tag gavin for review of items closed so he has the option to see.
