### ISSUE TITLE
Games pages videos section css re-style

### ISSUE THREAD

**Issue by jasonGonzales33** [e-sportsdotcool/esports.web#199]

**Comment by ppantilla** [comment]
just a couple of edits:

1.  text is currently #ffffff - best to make it something less contrast-y for it to be easier on the eyes, say #fefefe.

2. Set font to be less bold, if possible.

**Comment by ppantilla** [comment]
also the footer format is screwed up, might not be the same footer as in the home and community page

**Comment by ppantilla** [comment]
format of the article text is also a bit tired.  perhaps a better looking article speciffc layout ?

**Comment by jasonGonzales33** [comment]
deployed to prod
