### ISSUE TITLE
Update content via CMS

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#20]
Start adding updated content via CMS. Need a session to go through the interface & process for updating CMS.

**Comment by ppantilla** [comment]
changed you to user permissions for administrator; you should be able to log in in the backend: http://45.58.45.127/administrator/index.php

**Comment by ppantilla** [comment]
can walk you through anytime you want.  just did a backup too

**Comment by ppantilla** [comment]
saw you've made some edits.   let me know when you want a runthrough

**Comment by laisee** [comment]
How's tomorrow for you

**Comment by ppantilla** [comment]
im good in the morning.
