### ISSUE TITLE
restore video background to home page

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#201]
reference: http://45.58.40.76/static/

**Comment by ppantilla** [comment]
try using this: https://joomlead.com/g5/docs/video-background-atom-documentation/

**Comment by ppantilla** [comment]
you can just grab the html code from prod for the wording code (search for hero) among the modules

**Comment by ppantilla** [comment]
great job, is there a way to make it full width of the browser?

**Comment by ppantilla** [comment]
you can close this after

**Comment by jasonGonzales33** [comment]
deployed to prod
