### ISSUE TITLE
Gantry 5 Outline Assignments Not Appearing on Front End

### ISSUE THREAD

**Issue by jasonGonzales33** [e-sportsdotcool/esports.web#202]
It seems it has been a FAQ since it is on the documentation (http://docs.gantry.org/gantry5/troubleshooting/assignment-issues)

it says the issue is with third-party plugins but I am not sure which one might be causing it.

*Identify the problem or seek help on forums/support

**Comment by ppantilla** [comment]
sorry what do you need an outline for?

**Comment by jasonGonzales33** [comment]
for when i need a page to have specific outline - whenever i assign a page to a particular custom outline, it doesnt, then proceeds to default to the default template

**Comment by jasonGonzales33** [comment]
Found the problem. According to my research, it seems that some Joomla extensions break the Gantry 5 template assignments. Disabling these extensions (mainly sellacious ones - I uninstalled them) fixed the outline assignment issue.
