### ISSUE TITLE
Set up steam bot

### ISSUE THREAD

**Issue by jasonGonzales33** [e-sportsdotcool/esports.web#212]
this includes getting premium account (load at least $5 into steam wallet) and aquiring skins for trade offer testing

**Comment by jasonGonzales33** [comment]
![3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cba5677fb6900011a39579/125516c66e82c728ace21e0d46bbd6d6619291a685ecbc57e607b2c1701175777951a77e7384b52ab9122b560a094bf9400a0e56e0ebcb7af8e2632dd3165eafc3674d75ce3710a9ba831abc07bd278c4985bfaec7.png)

Image above describes the current issue with the tinwald Steam account.

However, my freind knows a store that sells Steam Wallet Cards at the mall. I'll see if I can set up my personal Steam account as our Steam bot.

**Comment by jasonGonzales33** [comment]
Headed to the mall now. Confirmed that DataBlitz sells Steam Wallet Cards. I'm gonna top-up my account with at least $5 to be able to reach premium level

**Comment by laisee** [comment]
Y85PH

**Comment by jasonGonzales33** [comment]
Went to the mall, they said they only had the the Php 500, the 1k and the 2k. They charged Php 570 for the 500 valued one. I only brought 500 with me so that did not go well.

However, I had the chance to talk to one of the guys there who played DOTA and uses the Steam market. It seems that even if I did load in an account with $5, I would have to wait 30 days for me to able to use the market...
(https://support.steampowered.com/kb_article.php?ref=1047-EDFM-2932#purchase)

Anyway, I will still try to make use of the tinwald/pompokey Steam account even though it currently has restrictions because of the recent password changes (perhaps the API will not restrict me)

**Comment by jasonGonzales33** [comment]
Going to use 'pompokey' as the steam bot. have code ready.. just waiting for restrictions to end. 

Simple logic: 

- The steam bot pompokey should always be logged in.. pompokey is to accept all incoming trades from a user that wants to sell an item. pompokey is to send a trade offer to client upon cart checkout (im using halipso library for the bot)

- User logs in the site (using e-sports.cool account), after this step the landing page is to verify if the user has a steam account connected to it.. if NOT: then ask for the user to link his/her steam account. (im using LightOpenID library for the steam authentication)

- Ask for the user trade URL if it is not set.. (it is one of the parameters needed for trading)

- How to buy: user picks item he/she wants then checkout via cart page, pompokey sends trade offer to user, user accepts trade offer via steam (basically href button to trade offers page), check if trade accepted, if all is well: user auto sends COOL to the seller of the item. Send notifications after.

- How to sell: user picks item he/she wants to sell, user trades items to pompokey via steam (basically href button to trade url of pompokey), user then waits for item to sell. If items sells: buyer auto sends cool to user. Send notifications after.

**Comment by jasonGonzales33** [comment]
![steam guard mobile.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cba5677fb6900011a39579/125516c66e82c728ace21e0d46fb809f228fc3ae9ae8ad47e450ff96204a22316546b3397f8fe62bab0021435a5649ae15585a10f9aad82df4e03c708d095de8846c0d25d42103eee9dc4be05ce36ade0d97bcae8b44cae93827e483864b3c1e01108df94f78.png)
