### ISSUE TITLE
SUBTICKET TO 98 - Add twitch icon/url to header, footer

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#22]
Add this link to header & footer alonside facebook, instagram, etc

https://www.twitch.tv/esportsdotcool

see twitch.tv for icon

**Comment by laisee** [comment]
managed to add "Twitch.tv" link at top but the icon doesn't show. I notice the icon field is not even populated for Facebook, Instagram, Twitter. Can you let me know how it works?

**Comment by ppantilla** [comment]
Sure.  All you need to do is go to Dropdown Menu Options for the menu item, fill in the field Menu Icon with the appropriate css class name "icon-""<social network>

**Comment by ppantilla** [comment]
Other notes for the twitch icon. Seems that icon-twitch is only available in font awesome 4.2 which is with the later version of Gantry, our template's underlying framework. As we cant be assured that nothing will break in our rt-paradigm, i suggest we defer the icon update until we are ready to get the licensed copies of the template as well as easysocial.

**Comment by ppantilla** [comment]
again if we can prototype using afterburner2 template with either an updated font awesome / or some other way that twitch icon can  be made available that would suffice

**Comment by ppantilla** [comment]
verified as available in helium gantry 5 template.  will put up for review once the template is on staging.

**Comment by ppantilla** [comment]
included in helium deployed to prod
