### ISSUE TITLE
Cool Token Sender is Constant

### ISSUE THREAD

**Issue by jasonGonzales33** [e-sportsdotcool/esports.web#223]
Whenever user sends Cool, the sender is constant.

the sender is always "ND2ZED-4NP2MG-EKPKBU-OTPAXQ-MMJDP2-BTL5NK-OLVV"

the recipient is correct, though.

I may need help with this one as it is not my code and I do not know where to start. (my html form code on joomla is not the culprit - i have triple checked and all my fields are correct)

**Comment by jasonGonzales33** [comment]
This is done. deployed to staging & production site.

I changed the redis implementation into a simple sql select structure.

...working now as intended for both Profile Send Cool and Skin Artist Purchase (Skin Artist Features are only currently in staging though - I haven't deployed the Skin Artist Features to Prod because they are still yet to be reviewed)

Anyway my account NDXM33XVOPTX4WF4BJ44IHXTRNIKBMUIH6VDEAXE
has 0.149999 XEM left because of tests.
If you guys could lend me some for future testing , that would be awesome.

**Comment by laisee** [comment]
We had this question last year, I was under impression the sender had been
into a  dynamic property
