### ISSUE TITLE
Steam Authentication

### ISSUE THREAD

**Issue by jasonGonzales33** [e-sportsdotcool/esports.web#224]
I need session id, cookies, and api key of steam user for the trade offering to work

**Comment by laisee** [comment]
shall I try to get an API key issued on my account?

**Comment by jasonGonzales33** [comment]
No, it's fine. Since creation/acceptance of a trade offer is not included in the API,(https://developer.valvesoftware.com/wiki/Steam_Web_API/IEconService) 

I am coding to automatically get user's API key upon login from steam. The code will need those three things (session id, cookies, and api key) to make request for the trade offer

here is a sample very important line of the code:
$response = Unirest\Request::post('https://steamcommunity.com/tradeoffer/new/send', $headers, $formFields);

// $headers here is the cookies
// $forFields here is an array. one of the data inside the array contains the session id
