### ISSUE TITLE
Error: Unknown address "NBFUO2QMTL7H57W42TK6R4MUADKVADUHXRUVO5KM" used in Transaction/new method

### ISSUE THREAD

**Issue by jasonGonzales33** [e-sportsdotcool/esports.web#226]
This particular address is not working when sending COOL.
i don't know what's going on though...

Can you guys give me access to the Heroku App error logs so i can review?

**Comment by laisee** [comment]
Let me forward to you.

**Comment by jasonGonzales33** [comment]
The reason behind cool send fails from this address is because there is a whitelist of addresses that are permitted to send cool (this address is not one of the permitted) ... closing

**Comment by laisee** [comment]
Jason,

I need the private key for that address to enable sending COOL tokens.

You can find it un the Nano wallet

Gavin

**Comment by jasonGonzales33** [comment]
Ah its fine. this address is from a test account... it is not imperative that I gain access to send cool functions with this address

This is the address im using - NDXM33XVOPTX4WF4BJ44IHXTRNIKBMUIH6VDEAXE and it is fully functional

I was just testing other accounts when i was doing ticket 221

Also, im not really sure where to view the private key ...

**Comment by laisee** [comment]
Ok, if you have another one that works just use that in your profile

You can find private keys in the online wallet. Google for NEM wallet

gavin

**Comment by jasonGonzales33** [comment]
![Untitled.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cba5677fb6900011a39579/125516c66e82c728ace21e0d46dd9a8e2a968fac8babf301b44fff9e2c4533317346f67227d7e778ea462e020e591cfa41585811aafcdc2af4e72e6c981e5ab38532022d8c6853beb2901eb60bbb25894d81b7b48b4cc3ee3426f5c6.png)

This is where I mostly view address details.. But current logged in wallet is a wallet that I made. I can only see details here such as public key, XEM balance, transaction logs, etc... (see image)

I assume i need to import the e-sports wallet? that contains the address concerned? is this correct?

**Comment by jasonGonzales33** [comment]
in order to view the private key, i mean
