### ISSUE TITLE
Display loot box "possible content"

### ISSUE THREAD

**Issue by jasonGonzales33** [e-sportsdotcool/esports.web#300]
If the item is a loot box, display what it could possible contain when opened

**Comment by laisee** [comment]
Is this possible? Could we run some kind of lottery or auction for loot box
content?

**Comment by jasonGonzales33** [comment]
Yeah, I imagine we can do it for any item - not just loot boxes

**Comment by jasonGonzales33** [comment]
For example, if a user is trying to sell his item not for a certain price - for example if he is trying to fish for offers
