### ISSUE TITLE
Update list of games for popularity

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#33]
https://y4j7y8s9.ssl.hwcdn.net/wp-content/uploads/2017/01/GameTiers_Jan17_Hilgers.jpg

**Comment by ppantilla** [comment]
Note to self.  Build Overwatch content areas, might be good to separate the games by these tiers in the menu, i.e. A-List (for tier1), Challengers  (tier2),  Upcoming (tier3)

**Comment by laisee** [comment]
Good idea. Could also filter games so fans avoid stuff they don't care about

**Comment by laisee** [comment]
see also list of top 10 games viewed on twitch: https://newzoo.com/insights/rankings/top-games-twitch/

**Comment by ppantilla** [comment]
pretty consistent with the tiering, but its interesting to see that starcraft 2 has a sizeable % of the esports share, what that may mean should probably be checked...

**Comment by laisee** [comment]
Any way to find out which is biggest game in Philippines?

**Comment by laisee** [comment]
see game revenue by country @ https://newzoo.com/insights/rankings/top-100-countries-by-game-revenues

**Comment by laisee** [comment]
see most played core PC games @ https://newzoo.com/insights/rankings/top-20-core-pc-games/

**Comment by laisee** [comment]
closing as this is covered by other tasks
