### ISSUE TITLE
Change BB Points to "COOL Tokens" in UI

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#35]
remove BB Points test. COOL tokens are now issued and we can use as soon as the user accounts are linked to NEM wallers

**Comment by laisee** [comment]
text to be changed in easysocial panel for user:
![Screen Shot 2017-08-21 at 7.11.57 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6456f26b7191a37ff1132a4f5a585ecc3c4a4356bcbbd671f3e57862804e0ee4d66f0b74c36914ffe9844de901ba27de1980e3bdd81dd2f42f67b6d5db1063474f4dcbed5727a29f41c95df648e24c51a0133765e3732431.png)

**Comment by laisee** [comment]
number of COOL tokens available: 9 billion
![Screen Shot 2017-08-21 at 7.17.47 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6456f26b7191a37ff1132c4f5b585ecc3c4a4356bcbbd671f3e57862804e0ee4d66f0b74c36914ffe9844de901ba27de1980e3bdd81dd2f42f67b6d5db1063474f4dcbed5727a59a4fca52f74ee14e56a5173267e270337e55d9.png)

**Comment by ppantilla** [comment]
the points system here can be deactivated.  it's probably better to do that instead of  trying to tie the two together.

**Comment by ppantilla** [comment]
unless you would like to award tokens for behaviors in the same way

**Comment by laisee** [comment]
I would like to reward users, but direct points to their COOL wallet instead. Can be developed as new feature or the current points code could be enhanced

**Comment by ppantilla** [comment]
I would imagine that there will be a lot of areas by which rewards can be earned within the site but not necessarily within just easysocial so it might make sense to go for a new feature and marry code into that.

**Comment by laisee** [comment]
Yep. Quite true. We can do some planning next week in Manila

**Comment by ppantilla** [comment]
Placeholder:  current direction will be to make a custom fork of AltaUserPoints for the implem.

**Comment by laisee** [comment]
ideas for COOL points :
- award 1000 for signing up (need to ensure no duplicates and points not available unless user logs in X times in first Y days)
- award COOL for bringing buddies online (25) - can use joomla affiliate/referral component 
- award COOL for adding new leagues, teams, events, reviews (TBD)
- award COOL for being active on site e.g. logging in 5 days out of 7
- award COOL for the events listed under the existing Points system. 
- award COOL if your referrals top the lists for COOL awarded this week/month
