### ISSUE TITLE
Review e-sports site features

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#36]
confirm what is available, what is to be added
- user account features(list)
- easysocial features(list)
- wallet features
  > balance (one wallet at 1st) ==> DONE
  > transactions list ==> DONE
  > send/receive to other e-sports.cool users ==> DONE
  > pay for stuff (weapons, skins, etc) ==> TODO
- Game Schedule ==> TODO
  > game calendar
  > alerts
  > send schedule on weekly basis
  > include twitch.tv links
  > export listing to csv, outlook etc
- Shop (skins, weapons, shirts, hats etc) ==> TODO
  > pay with NEM/Tokens
  > may have c/card option
- Video(twitch.tv, Hitbox.tv, GamingLive.tv) ==> TODO 
Ability to add links to streamed content for replay 
- Trading (tokens, assets, skins, loot boxes) ==> TODO
- Contests (raffle for online players, quizzes, etc) ==> TODO
- Content (p/p/view, tipping, paid blogs, channels, re-sale with commission share) ==> TODO

**Comment by ppantilla** [comment]
user account features:  standard Joomla user access control via user groups ( public, guests,registered, author, publisher administrator super user)

**Comment by ppantilla** [comment]
Easysocial features:  Groups with Events, Discussions (forums)

**Comment by laisee** [comment]
EasySocial seems have a few extra Apps, did not see many useful to e-sports site, tho.

**Comment by laisee** [comment]
close & keep as source of features
