### ISSUE TITLE
Initialize user wallet when account created

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#37]
generate new wallet(account) when user signs up
 - invisible to user, no action required
 - no need to show address or public key
 - we will probably load 1000/10000 tokens for each account, but tokens can't be spent until user confirms sign up and logs in X times in 1st month.

**Comment by laisee** [comment]
Comments from EasySocial support(StackIdeas.com)

"Rather than hacking the codes in EasySocial (because you will need to re-apply the hacks each time you upgrade EasySocial), it is best for you to create an app in EasySocial.

Take a look at some of the sample apps under /media/com_easysocial/apps/user/ and duplicate the folder. Rename it accordingly and within your app's file, you just need to add a method called onUserAfterCreate . This gets triggered when a user is created on your site."

**Comment by laisee** [comment]
added REST call to generate wallet, load X thousand tokens and pass back wallet address to calling PHP code. 

REST URL: http://esports-wallet.herokuapp.com/wallet/new/<user id>
 user id to be passed in so the call can be tracked in case of error and for auditing

**Comment by laisee** [comment]
I have built REST call for initializing wallet & assigning COOL tokens to the new account. Need to add the REST call into the account opening method/hook ES support mentioned.

**Comment by laisee** [comment]
whats the status for the item, Peter?

**Comment by ppantilla** [comment]
will need to move this back to active, need to retest for error handling.

**Comment by ppantilla** [comment]
rewrote transaction data save routine to be inserts vs updates. testing tomorrow

**Comment by ppantilla** [comment]
creation of wallet and saving of returned details successful, just dont see the 1000 cool tokens allocated to the account though.  putting up for review.

**Comment by laisee** [comment]
Will check for any errors tomorrow. You are seeing a new wallet address for
each account created?
