### ISSUE TITLE
Peter to set meeting with TNC owner for  feedback,entry point

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#40]
Peter to set meeting with TNC owner for  feedback,entry point for signing up teams, possible x-deal -> publicity vs engagement / promotion on esports.cool

**Comment by ppantilla** [comment]
sent out feelers on fb to the tnc pro team last night. will continue seeking ...

**Comment by laisee** [comment]
great. can spend on coffees, lunches as needed to establish contact.

**Comment by ppantilla** [comment]
contacted the philippine esports organization, which seems to be just one guy.  lets see  if he bites

**Comment by laisee** [comment]
Cool. Please follow up with hearthstone lady and ask for some 2 - 3
articles we can post.

On 7 Sep 2017 11:24 a.m., "Peter Pantilla" <notifications@github.com> wrote:

contacted the philippine esports organization, which seems to be just one
guy. lets see if he bites

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/e-sportsdotcool/esports.web/issues/40#issuecomment-327673079>,
or mute the thread

**Comment by ppantilla** [comment]
lady from Upwork dumped us for other  jobs.  will send the message nonethelsess

**Comment by laisee** [comment]
Tell her we are always interested in content, she can get in touch when she
has free time

Gavin

**Comment by laisee** [comment]
Any updates on the esports/philippines guy or hearthstone lady?

**Comment by ppantilla** [comment]
none, but reposted the job and invited some e-sports writers to apply, should get something back soon

**Comment by ppantilla** [comment]
sent out about 5 or so invitations

**Comment by laisee** [comment]
https://spout360.com/games/features/dota2/philippines-esports-cyber-cafe-father-shares-the-secret-to-his-success

**Comment by ppantilla** [comment]
probably good to finish tambayan before we go to talk to this guy

**Comment by laisee** [comment]
Yes. Also like to meet up with the guy from NEM meeting @ Quezon City,
possibly next time I am in town. Would be more of a introductory/coffee
than any specific business proposal.
