### ISSUE TITLE
Incoming TX Notification

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#41]
- design visual aspects
- Define info display ("you have 88 COOL incoming")
- user can Click any place to go to TX List?

**Comment by laisee** [comment]
for example, we could make the Balance light up or jiggle or change color when there is incoming TX.

**Comment by laisee** [comment]
code up sample for individual user being notified by ably-backed web service

**Comment by laisee** [comment]
js code for  receiving notifications on new txns:
See entire code set with html at https://jsbin.ably.io/ajuwaz/8/edit 

var clientId = 'Gavin88';

function authCallback(tokenParams, callback) {
  var rest = new Ably.Rest({ key: 'v1MMcQ.xdLtSQ:_7nGMd2wHjZKUncS' });
  rest.auth.createTokenRequest({ clientId: clientId }, function(err, tokenRequest) {
    show('Token request created for clientId: ' + tokenRequest.clientId, 'orange');
    callback(null, tokenRequest);
  });
}

var realtime = new Ably.Realtime({ authCallback: authCallback }),    channel = realtime.channels.get('esports.wallet.gavin88');

realtime.connection.on('connected', function() {
  show('✓ Connected to Ably with clientId: ' + realtime.auth.tokenDetails.clientId, 'green');
});

channel.subscribe(function(message) {
  show('⬅ Received message '+message.data+' with clientId: ' + message.clientId, 'green');
});

function show(status, color) {
  $('#realtime-status').append($('<li>').text(status).css('color', color));
}

**Comment by ppantilla** [comment]
do all the code in the link (HTML, CSS, JS) need to be in the page? sorry just glanced at this.

**Comment by laisee** [comment]
Nah. probably only the JS is mandatory. the data display and styling is up
to you.

for example, we could make the balance change color when incoming funds
received and show data on the transaction in mouseover.

**Comment by ppantilla** [comment]
check this out for a start.....

**Comment by laisee** [comment]
The Ninja is now reacting to incoming TX which is great. Next the details of the TX should be displayed somehow (mouseover, tool tip, ticker of events like new TX running across the top of the page, ...)

Also, we should make it easy to substitute different icons so we can run A/B testing and use feedback from fans on the COOLest Ninja designs.

**Comment by ppantilla** [comment]
do we still want to do this vs. the current hide button?

**Comment by laisee** [comment]
Yes, but we could just go for small visual clue until ninja design done.
For example change ninja image to "wallet is up to date" or "transaction
processed" text or images.

**Comment by laisee** [comment]
moving back to ready until we assign resource to closing this.

**Comment by ppantilla** [comment]
got a set of ninja images that will probably work better.  will put that together in my free time over the next 2 weeks

**Comment by ppantilla** [comment]
related to ninsei ticket

**Comment by jasonGonzales33** [comment]
trigger
https://jsbin.ably.io/ajuwaz/15/edit

**Comment by jasonGonzales33** [comment]
having a bit of trouble for quite some time now
the code & logic is ready to be deployed, but this error keeps popping up upon assigning the ably script:

Uncaught TypeError: jQuery(...).tooltip is not a function

**Comment by jasonGonzales33** [comment]
i instead implemented ably using php.
git/document is here: https://github.com/ably/ably-php
code now works and will be deploying to 76 & prod soon

**Comment by jasonGonzales33** [comment]
done.

if you guys want to test without spending XEM for the transfer fee,
use this link: https://jsbin.ably.io/ajuwaz/15/edit

just change parameters for this function: channel.publish('63', '707', function(err)

'63' here is amount of cool
'707' here is easy social user id
