### ISSUE TITLE
account header/detail widget

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#44]

**Comment by laisee** [comment]
display is missing some/all of the transaction COOL amount data
![Screen Shot 2017-09-04 at 4.51.19 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772a6454f76b7191a37cf1172a4f5e565ecc3c4a4356bcbbd671f3e57862804e0ee4d66f0b74c36914ffe9844de901ba27de1980e3bdd81dd2f42f67b6d5db1063474f4dcbed5727a19e41c95df64fe44c50a5163e65e37e2431.png)

**Comment by laisee** [comment]
Issue is still happening last time I looked

**Comment by ppantilla** [comment]
Compressed the widget html, removed the word Transaction to pulldown the details.  Working on the bug next.

**Comment by ppantilla** [comment]
rewrote implementation, algo is much more straightforward now.  Assumes that a transaction will only have one instance of a mosaic entry in the JSON response.

**Comment by laisee** [comment]
Works Ok now.
