### ISSUE TITLE
Why did we build e-sports.cool?

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#52]
write content for web page, add page to site, update footer link

**Comment by laisee** [comment]
article created, ready to be assigned to web page in joomla

**Comment by ppantilla** [comment]
please send link so i can publish

**Comment by ppantilla** [comment]
cant find this. on staging or prod.  is the title different ?

**Comment by laisee** [comment]
[Uploading Why-did-we-build-esportsDotCool.txt...]

**Comment by laisee** [comment]
added context in attached file. Please add the names/icons at bottom of page.

**Comment by laisee** [comment]
Also fix the google+ icon listed in header and footer - contains link for facebook.com

should be https://plus.google.com/u/0/102691477999918463422

**Comment by jasonGonzales33** [comment]
@laisee the file did not upload (its waffle.io uploading bug - happened to me before) please upload again

**Comment by jasonGonzales33** [comment]
google+ icon redirects correctly & article is set on footer
