### ISSUE TITLE
Can I buy COOL Tokens?

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#53]
write content for web page, add page to site, update footer link

**Comment by laisee** [comment]
Content for web page is 

"COOL tokens can only be generated on e-sports.cool site when people create a new account or send tokens back and forth among user accounts. Future plans include using COOL tokens to buy merchandise like t-shirts, gaming gear and other cool stuff."

**Comment by laisee** [comment]
please use the content in first comment to create page linked to the "Can I buy COOL tokens" link in footers.

**Comment by jasonGonzales33** [comment]
page added. link in footer updated.
