### ISSUE TITLE
Add content for static pages

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#55]
About E-Sports - DONE
Contact Us - DONE (content, page to be published)
Legal & Privacy - Removed
Careers - Removed
FAQ - DONE(content, page to be published)
Support -DONE(content, page to be published)

**Comment by laisee** [comment]
add "Contact Us" page connected to the "Contact Us" link on footer

**Comment by laisee** [comment]
updated FAQ, removed old FAQ article but could not save the new one as it says the alias is still being used

**Comment by jasonGonzales33** [comment]
added support page, made changes to faq. updated footer (linked to the pages)

**Comment by laisee** [comment]
Looks OK. Closed
