### ISSUE TITLE
Research Gaming Culture - Top 10 games

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#57]
Placeholder for useful info, links and docs on e-sports

**Comment by ppantilla** [comment]
Social Media venues: Reddit ( for general info/game news), Steam (community) & Discord (Instant Messenger, in-game window)

**Comment by ppantilla** [comment]
https://boards.na.leagueoflegends.com/en/c/esports/wGjBy44j-letter-to-riot-community-prized-events-feedback

**Comment by laisee** [comment]
Wikipedia  https://en.wikipedia.org/wiki/League_of_Legends

**Comment by laisee** [comment]
added docs (one in word, one in PDF format) from fiverr.com gig

**Comment by laisee** [comment]
[gaming_list_top_10.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46ef95972a8c849683e0ac579b49ff84161777316546b3397f8fe62bab0021435a5649ae15585a10f9aad82df4e03c708d095de8846c0d25d42103eee9dc4be05ce36ade0d97bcae8b44cae93825e18e894c3b1c01108aff4f78.pdf)
[gaming_list_top_10.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46ef95972a8c849683e0ac579b49ff84161777316546b3397f8fe62bab0021435a5649ae15585a10f9aad82df4e03c708d095de8846c0d25d42103eee9dc4be05ce36ade0d97bcae884ccae93825e18e894c3b1c001a8ffc4f78.docx)
