### ISSUE TITLE
Separate Incoming/Outgoing txns

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#59]
Find out how to separate incoming/outgoing txns

**Comment by ppantilla** [comment]
There's separate NIS requests for both incoming and outgoing.  So the easy way is to just issue 2 requests.  Otherwise, as discussed, it can be gleaned by who is the sender and receiver address.

**Comment by laisee** [comment]
Can you let me know the two calls? I will update my notification service.

**Comment by laisee** [comment]
updated service to return all transactions
