### ISSUE TITLE
Format timestamp into UTC/Local display

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#60]
sample code:

var timestamp = 76669454;
var timestamp = 76923356; // 07:42:21 AM (UTC)
var NEM_EPOCH = new Date(2015, 2, 29, 0, 6, 25, 0);
NEM_EPOCH.setSeconds(NEM_EPOCH.getSeconds() + timestamp);
alert(NEM_EPOCH);

**Comment by ppantilla** [comment]
fixed this, adjusted fee to be / 1000000 and fixed alignment.  code for timestamp is  date( 'Y-m-d H:i:s' , $transaction_arr_val + 1427587585)
