### ISSUE TITLE
Add Major Tournaments(5) per Game

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#62]
task for Angel to add easysocial events wth details on when/where/who.
start with 5 events per game, then review and add more each week(guessing)

**Comment by laisee** [comment]
Content for events can be found at
- Smite: esports.smitegame.com
- DOTA2: wiki.teamliquid.net/dota2/Major_Tournaments
- Starcraft2: wiki.teamliquid.net/starcraft2/Major_Tournaments
- Hearthstone: wiki.teamliquid.net/hearthstone/Portal:Tournaments
- Counterstrike: wiki.teamliquid.net/counterstrike/Premier_Tournaments
- Clash of Clans: www.toornament.com/games/clash_royale (use the data for now, although wrong game title). Will change "Clash of Clans" to "Clash Royale" on e-sports.cool site
- LOL: www.lolesports.com/en_US/na-lcs/na_2017_summer/schedule/regionals/Round%201

**Comment by laisee** [comment]
assigned to Angel

**Comment by rotaangela1211** [comment]
Gavin, here the the stuff i posted so far

9 events of ESL Pro League EU (CSGo)
ESL Pro League VI: Sept27-Oct 6
https://www.toornament.com/tournaments/593005992339505152/matches/schedule?page=1
ESL Pro League VI: Oct 6-Nov. 12
https://www.toornament.com/tournaments/593005992339505152/matches/schedule?page=2

1 event  ()
FroggedTV Brawl
https://www.toornament.com/tournaments/712005192326201344/registration/

1 event
Arx Community League(DOTA 2)
https://www.toornament.com/tournaments/733096237972406272/information

1 event (DOTA2)
SL i-League Invitational Season 3
http://wiki.teamliquid.net/dota2/StarLadder/i-League_Invitational/3

1 event (DOTA2)
 The Major League
http://wiki.teamliquid.net/dota2/The_Major_League/Malaysia_Qualifier

1 event (DOTA2)
PGL Open Bucharest
http://wiki.teamliquid.net/dota2/PGL_Open/Bucharest/2017

1 event (ClashRoyale)
The Royale Prime
https://www.toornament.com/tournaments/475848179887874048/information

1 event  (DOTA2)
Vios Dota 2 Tournament 
http://challonge.com/2o94tdin

1 event (DOTA2)
Swiss Dota League Qualifier
https://www.toornament.com/tournaments/436324280877206590/information

1 event (ClashRoyale)
Clash Royale, Night Rush
https://www.toornament.com/tournaments/732716362512875520/registration/

**Comment by rotaangela1211** [comment]
Hi Gavin, here are the stuff i posted yesterday, Sept. 19
League of Legends (5 events)
Play-in, Group stage, Quarter Finals, Semi-Finals, Finals
http://www.lolesports.com/en_US/articles/2017-international-events

**Comment by rotaangela1211** [comment]
Posted events on Sept.  20

Star Craft (2 events)
2017 AfreecaTV GSL 
http://wiki.teamliquid.net/starcraft2/2017_AfreecaTV_GSL_Super_Tournament_2

2017 WCS Global Finals
http://wiki.teamliquid.net/starcraft2/2017_WCS_Global_Finals

Hearthstone (1 event)
2017 Hearthstone World Championship

Smite (8 events)
1.Battle For Valhalla - August Championship
http://www.smitecentral.com/content/tournaments/page/5v5/battle-for-valhalla-september-championship-tuesday-september-27th

2. BATTLE FOR VALHALLA OCTOBER CIRCUIT #1 |OCTOBER 4TH
http://www.smitecentral.com/content/tournaments/page/5v5/battle-for-valhalla-october-circuit-1-tuesday-october-4th

3. Battle For Valhalla - October Ciruit #2
http://www.smitecentral.com/content/tournaments/page/5v5/battle-for-valhalla-october-circuit-2-tuesday-october-11th

4. BATTLE FOR VALHALLA OCTOBER CIRCUIT #3 |
http://www.smitecentral.com/content/tournaments/page/5v5/battle-for-valhalla-october-circuit-3-tuesday-october-18th

5.Battle For Valhalla - October Championship
http://www.smitecentral.com/content/tournaments/page/5v5/battle-for-valhalla-september-championship-tuesday-october-25th

6. Battle For Valhalla - November Ciruit #1
http://www.smitecentral.com/content/tournaments/page/5v5/battle-for-valhalla-november-circuit-1-tuesday-november-1st

7. BATTLE FOR VALHALLA - NOVEMBER CIRUIT #3
http://www.smitecentral.com/content/tournaments/page/5v5/battle-for-valhalla-november-championship-5v5-conquest

8. BATTLE FOR VALHALLA NOVEMBER CIRCUIT #2 | 
http://www.smitecentral.com/content/tournaments/page/5v5/battle-for-valhalla-november-circuit-2-tuesday-november-8th

**Comment by laisee** [comment]
Thanks for update

**Comment by rotaangela1211** [comment]
ooops, I'm sorry. Some events  I've posted were dated last year pa pala. All the  Smite events scratch those

**Comment by laisee** [comment]
We will keep them as historical records. Please check dates in future,
thanks

**Comment by ppantilla** [comment]
note: we'll keep these as Easysocial events as we originally had.  I'll be removing all non-COOL tournaments from Joomsport.

**Comment by laisee** [comment]
K. Did joomsports give any ideas for sharing events across the two
components? Can we have joomsports tournaments included in events stream?
