### ISSUE TITLE
Switch to HTTPS(atlantic, heroku)

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#64]
change the protocol used from http to https

**Comment by ppantilla** [comment]
found tls ca offering free and other class level certificates, let me know if this is ok or you already have a cert: https://www.startcomca.com/?app=40

**Comment by laisee** [comment]
Don't have cert. Would these be compatible on atlantic.com and heroku.com
(or amazon.com)?

**Comment by ppantilla** [comment]
the free one is just for browsing, i found one for apache on ubuntu 16.04

**Comment by ppantilla** [comment]
need a bit of help, am setting up free ssl cert from let's encrypt and the setup script is being refused a connection to the DNS records.   need to check DNS entries and access.
