### ISSUE TITLE
Handle negative quantity in UI

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#68]
user can send -negative quantity for SEND Transfers. Back end will raise an error - UI needs to handle the error returned from back end

**Comment by ppantilla** [comment]
placed front and backend restrictions for quantity input to be + numbers only.

**Comment by ppantilla** [comment]
deploying to prod

**Comment by laisee** [comment]
can you adjust the check to stop any 0 value transfers @ front end. back end will reject the 0 transfers as a fallback check
