### ISSUE TITLE
Add checks & success/failed send handling

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#72]
Currently the send operation shows success/failure text in web site text box/label. 

Change this so the user gets a popup with status and result ("Transfer completed for XX COOL to Tynwald" or "Error - could not send due to XXXX"). 

Send should also generate a notification to the sender & receiver.

**Comment by laisee** [comment]
Also - add validation before sending (check user balance & limit send to <= user Bal, check that non-numeric entry & amounts < 0 are not sent)
In addition, send function should check for any other transactions in progress to block user from sending multiple times from multi tabs (this is extra work, probably best to add to backlog)

**Comment by laisee** [comment]
moved to jason, so he can enhance the popup and add validation

**Comment by laisee** [comment]
also ensure that after successful send the user gets taken back to the profile page he initiated send on. currently the code lands user in empty page.
![Screen Shot 2017-10-13 at 5.27.48 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236455f06b7191a37df1102c4f5b575ecc3c4a4356bcbbd671f3e57862804e0ee4d66f0b74c36914ffe9844de901ba27de1980e3bdd81dd2f42f67b6d5db1063474f4dcbed5727a19041c95df64ce94553ad1b316be67f2431.png)

**Comment by ppantilla** [comment]
which user did you send to?  currently already have code that routes back to the currently viewed sender but this is an exception

**Comment by jasonGonzales33** [comment]
re-opened. conversation still arrives when the transaction fails

**Comment by jasonGonzales33** [comment]
notifications no longer arrive when transaction fails

**Comment by jasonGonzales33** [comment]
re-opened. COOL amount needs handling

**Comment by jasonGonzales33** [comment]
the issue is not COOL amount. it is actually a bug on sender address. refer to ticket 151
