### ISSUE TITLE
Change Ninsei visual cue for incoming and outgoing tx

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#73]

**Comment by ppantilla** [comment]
lets open the floor for what this should be.  perhaps your graphic guy can make something a little more suibdued.  Or perhaps it can be another contract on fiverr?  As of now, we already have the change image points in code, so it will just be a matter of replacing the gifs

**Comment by laisee** [comment]
Asked the fiverr guy and he said he is not a gif guy. Will offer the image
and see what proposals turn up

**Comment by laisee** [comment]
![arriving-ninjas.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46e986882a948aa788a4b14aaa57f1876b0a65633b0ba92e7391a172fd1722565d0b4ea9155d0c15faabdf2ba6b169268f090abf807f4366846c4ff8e7df46f554f832815d84b1b68b49c0ee3424ef8c874c3f17030ac4.gif)
![dancing-ninjas.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46ec9594208b8daec2e7b64dae5ce3d665043761260ea62864c7b96aea1b2c530b5f4bf8440b0e42aeaf892ba1e36a75df5d59bcc3714d36976345f3e5db55ea43a82a994e82bcbd8f4cc6e13c2de0838c4e37191755.gif)

**Comment by ppantilla** [comment]
ill go with the first for now.

**Comment by laisee** [comment]
Switch to 1st GIF when incoming tx detected. Keep the GIF displayed for 10 secs and add entry to users incoming easysocial events. also change display of user balance to show (BALANCE) ++ (incomingoutgoing AMOUNT) while the transaction is within 48 hours of current date.

**Comment by laisee** [comment]
please pick this up in between tournament-related tasks

**Comment by ppantilla** [comment]
@jasonGonzales33  you can probably execute this at this point.

**Comment by laisee** [comment]
also, change the text on the button used for showing the COOL accounts so that when COOL accounts are displayed text will be "Hide COOL accounts"
[Uploading Screen Shot 2017-11-09 at 10.25.09 AM.png...]

**Comment by jasonGonzales33** [comment]
![1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cba5677fb6900011a39579/125516c66e82c728ace21e0d46b9d6d6619291a685ecbc57e607b2c1701175777951a77e7384b52ab9122b560a094bf9400a0e56e0ebcb7af8e2632dd3165eafc3674d75c13710a9b98217b903ba248a4983b4aec7.png)
