### ISSUE TITLE
Remove schedule from home page

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#74]
Schedule at bottom part of home page is out of date due to being static.
Remove it for now and add back when the schedule can be queried from DB, showing next events e.g. next 7  days

**Comment by laisee** [comment]
looks better, need to think about how site works for logged-in users vs guests.

**Comment by ppantilla** [comment]
yeah my thoughts still gravitate towards twitch,  would like to actually replace our welcome panels with videos, then video log feeds underneath

**Comment by laisee** [comment]
Good idea, something more dynamic.

Also like to display diskord chat in vertical panel somehow
