### ISSUE TITLE
Show user who sent/received COOL (not address)

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#75]
Want to hide the wallet address from tx list. May have a more detailed display showing technical info added later.

**Comment by laisee** [comment]
also, add column showing if the transfer was incoming/outgoing. perhaps column can hold and icon showing outgoing(red) and incoming(green) images

**Comment by ppantilla** [comment]
replace address with name perhaps?

**Comment by laisee** [comment]
Yes, should be name or handle of the sender/receiver. Handle("username") is
probably better as they can message the other person using that rather than
looking up someone's first/last name

**Comment by ppantilla** [comment]
helper code from ES:
Because the data of the user may / may not be stored as a string value, there is 2 methods that you could use.

* $user->getFieldValue("CUSTOM_FIELD_KEY";); - This is the pre-formatted value 
* $user->getFieldData("CUSTOM_FIELD_KEY";); - This is the raw data from the database

**Comment by ppantilla** [comment]
implemented in staging and verified

**Comment by ppantilla** [comment]
deployed in Prod and verified

**Comment by laisee** [comment]
Sent test transaction and user name doesn't show for user 'peter.pantilla'

![Screen Shot 2017-11-09 at 10.27.24 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226454fa6b7191a379ef0c2956415d4abc30254d58eeb9cb74fce36f34985619e8d86a5d20c63845a9ebd319ed57ba208c1ad3b3e98b1e91fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ae14c5ca0163066e376306e0a.png)

**Comment by ppantilla** [comment]
Ah my match test didn't strip dashes . I'll stick that in later

**Comment by ppantilla** [comment]
should be good now

**Comment by laisee** [comment]
works now
