### ISSUE TITLE
Balance widget shows when user not logged in

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#77]
Can see the balance widget after I log out. see attached image

**Comment by laisee** [comment]
![Screen Shot 2017-09-21 at 7.29.34 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58cfc23d15bc3d2000a54094/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772a6456f26b7191a37ff110224f5c5b5ecc3c4a4356bcbbd671f3e57862804e0ee4d66f0b74c36914ffe9844de901ba27de1980e3bdd81dd2f42f67b6d5db1063474f4dcbed5727a29841c95df64ee84456a1123565e5732431.png)

**Comment by ppantilla** [comment]
oops my slip showed.  done.
