### ISSUE TITLE
Monitor Upwork responses, interview candidates & select

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#8]
https://www.upwork.com/ab/applicants/890778130405277696/job-details

**Comment by laisee** [comment]
This JD looks good - maybe add some e-sports experience required?

https://www.jobsbank.gov.sg/ICMSPortal/portlets/JobBankHandler/SearchDetail.do?id=JOB-2017-0147681&source=JobsBank

**Comment by laisee** [comment]
web site for e-sports content provider: https://spout360.com

**Comment by laisee** [comment]
JD for e-sports content creator: https://www.internsg.com/jobs/detail/36149

**Comment by ppantilla** [comment]
i like this last one.

**Comment by laisee** [comment]
latest job post is at https://www.upwork.com/ab/applicants/913231087061348352/job-details

**Comment by ppantilla** [comment]
no access for some reason..

**Comment by laisee** [comment]
Removed and re-added both of our accounts in waffle. Pls try again

**Comment by ppantilla** [comment]
still no access.
