### ISSUE TITLE
Training: Platform

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#84]
Gain working knowledge in:
1. mysql or postgres
2. redis key/value store
3. php/python/javascipt
4. node.js
5. test frameworks (pytest, ??? for phph, mocha for javascript)

Any way you can demonstrate the learning would be good, live examples, plus probably we can have a review to see how much youve covered

**Comment by jasonGonzales33** [comment]
enrolled a python course at:
https://courses.edx.org/courses/course-v1:MITx+6.00.1x+2T2017_2/course/

will do exercises from time to time
