### ISSUE TITLE
Training: Joomla

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#86]
Research on the following Joomla packages:
1. Gantry 5 
2. Fabrik 
3. Easysocial 2 (will send references)

**Comment by jasonGonzales33** [comment]
- did interactive tutorials on fabrik via http://www.fabrikar.com/help/tutorials both lists and forms
- did back-end demo on EasySocial at http://easysocial.stackideas.com/administrator/index.php also front-end at http://easysocial.stackideas.com/
- did research on gantry 5 (youtube videos) on use of templates and gantry particles
