### ISSUE TITLE
Community Building

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#87]
Talk to cafes to broadcast/host tournament online

**Comment by laisee** [comment]
++ offer t-shirts, gaming time coupons, other prizes for activity on site

**Comment by laisee** [comment]
can you find a cafe that may be interested in running tournament with some prizes - helpos us expand user base and test joomlasport module.

**Comment by ppantilla** [comment]
thanks for pinging this one,  ill talk to the two cafes near here later today.

**Comment by ppantilla** [comment]
we have an affirmative from hoffman templato, the owner of tambayan.  will formulate the tournament mechanics

**Comment by laisee** [comment]
Great news ... When is the expected date?
