### ISSUE TITLE
Footer section a bit crowded

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#95]
Can see two parts to the footer, above and below the line. 

Suggest we drop the e-sports logo on left side, then reduce the vertical height for links above the line. Also make sure there is one copyright tag only.

**Comment by laisee** [comment]
add URL to each of the right side links also
 - facebook
 - instagram
- twitter
- twitch.tv

Link URL's can be found at the top of the web page

**Comment by jasonGonzales33** [comment]
see footer for changes made

**Comment by laisee** [comment]
close this item when it's been moved to http://e-sports.cool site

**Comment by ppantilla** [comment]
moved to prod, closing
