### ISSUE TITLE
Create new design for game pages 

### ISSUE THREAD

**Issue by ppantilla** [e-sportsdotcool/esports.web#98]
this will entail installing Gantry 5 and most likely Helium template on your local, and redesigning the landing pages for those games.  We want to move away from an intro to "sort of design" which is what it is now, to an information feed sort of lay out, featuring our team data that we are entering in Joomsport, as well as other content that we already have and will continue to have more of.   You can see design formats on egg.network and twitch.  Discuss design with @peter then proceed

**Comment by laisee** [comment]
Don't forget to include twitch.tv and diskord integrated into "home" pages
for each game. And later we will add merchandise and special offers based
on game and locations.

**Comment by jasonGonzales33** [comment]
http://45.58.40.76/jason/index.php/games/heroesofthestorm

**Comment by jasonGonzales33** [comment]
the link is the outline for the games pages I have created. please review

**Comment by laisee** [comment]
A lot of graphics, which looks nice, but I'm not sure it load fast and there is no navigation (links) visible until you scroll down. Also I'm wondering how it will run on mobile.

**Comment by jasonGonzales33** [comment]
have not linked all of the content yet. i will work on a different outline. this time will base it off of mineski.net, grids and everything. will add twitch streams module as well

**Comment by ppantilla** [comment]
perhaps we should explore using afterburner2 instead of moving up to gantry 5 for the meantime, if there is a way to get social media icons only on the top area to replace the current links that just use too much real estate, that should work for now

**Comment by ppantilla** [comment]
deprecated ticket as we have the UI rewrite on
