### ISSUE TITLE
SEO Optimization for site

### ISSUE THREAD

**Issue by laisee** [e-sportsdotcool/esports.web#99]
Optimize site for Search Engines, using suggestions from https://moz.com/blog/seo-your-joomla-website-in-11-super-easy-steps

**Comment by laisee** [comment]
1. Already done
2. Rename htaccess.txt to .htaccess - Outstanding
3. Enable SEF URLs and URL Rewriting - Outstanding
4. Remove "/images/" from your Robots.txt file - Outstanding
5. Install JCE Editor - Outstanding
6. Add alt tags and compress images - Outstanding 
7. Manage Your Meta Data - Done at Joomla global level. Install SEO Boss or not?
8. Choose www. or non-www. and Redirect - Outstanding
9. Be Consistent When Linking Internally - Outstanding
10. Speed Up Your Website!  - Outstanding
  - browser caching
  - image compression
  - enable gzip  
11. Install Xmap - Outstanding
12. Add SEO Components to Make Your Life Easier - Outstanding

**Comment by ppantilla** [comment]
Already done
Rename htaccess.txt to .htaccess - (done staging)
Enable SEF URLs and URL Rewriting - (done staging)
Remove "/images/" from your Robots.txt file - (done staging)
Install JCE Editor - (done staging) - user can set as preference)  
Add alt tags and compress images - spawning new ticket for Jason)
Manage Your Meta Data - Done at Joomla global level. Install SEO Boss or not? 
- looked good initially, evem if metas have decreased in significance.  Was put off though when i received a notice at download from Joomla.org saying that "This extension inserts backlinks to the developer and may impact SEO." :)

Choose www. or non-www. and Redirect - going with non-www as default, set .htaccess (staging)
Be Consistent When Linking Internally - Spawning ticket for Jason
Speed Up Your Website! - Outstanding
browser caching
image compression
enable gzip
Install Xmap - Outstanding
Add SEO Components to Make Your Life Easier - Outstanding

**Comment by ppantilla** [comment]
correction, OSMap breaks our Joomla instance.  manually removing the component

**Comment by laisee** [comment]
OPEN ITEMS
6. Add alt tags and compress images - Outstanding 
7. Manage Your Meta Data - Done at Joomla global level. Install SEO Boss or not?
9. Be Consistent When Linking Internally - (READY - Spawning ticket for Jason)
10. Speed Up Your Website!  - IN PROGRESS
  - browser caching
  - image compression
  - enable gzip  
11. Install Xmap - IN PROGRESS
12. Add SEO Components to Make Your Life Easier - IN PROGRESS

**Comment by ppantilla** [comment]
for #7, metas can be set for each content page.   the backlink penalty from gogole isn't something we want to have so we shoulldn't install this.

**Comment by laisee** [comment]
Agree, lets do that for each major page now (ignore FAQ, other static pages)

**Comment by ppantilla** [comment]
for 11, XMap is unavailable and unsupported, so we aren't doing that.   OSMap conflicts heavily with Easysocial 2, and there are no workarounds available, so better to have an externally generated XML sitemap generated and then loaded into prod.  I suspect that we may not be changing our primary menu structure very much that would necessitate a dynamically generated XML sitemap.

**Comment by ppantilla** [comment]
for the two SEO packages cited, sh404sef and artio, their primary selling point was the SEF friendly URL's which wasn't available at the time this article was written (2012) but is now part of Joomla core.  graceful 404 handling is already present with our template and in J3.5.1.

**Comment by ppantilla** [comment]
Browser cache script to be inserted in Prod (only) near steady state/launch:
<IfModule mod_expires.c>
  FileETag MTime Size
  AddOutputFilterByType DEFLATE text/plain text/html text/xml text/css application/xml application/xhtml+xml application/rss+xml application/javascript application/x-javascript
  ExpiresActive On
  ExpiresDefault "access plus 1 seconds"
  ExpiresByType text/html "access plus 600 seconds"
  ExpiresByType application/xhtml+xml "access plus 600 seconds"
  ExpiresByType text/css "access plus 1 month"
  ExpiresByType text/javascript "access plus 1 month "
  ExpiresByType application/javascript "access plus 1 month"
  ExpiresByType application/x-javascript "access plus 1 month"
  ExpiresByType image/x-icon "access plus 1 year"
  ExpiresByType image/jpeg "access plus 1 year"
  ExpiresByType image/png "access plus 1 year"
  ExpiresByType image/gif "access plus 1 year"
</IfModule>
